export const upper_imoticon_path = [
    {
        id:1,
        name:"ImotLove",
        kor:"사랑해",
        emo:"😍",

    },
    {
        id:2,
        name:"ImotNice",
        kor:"멋져",
        emo:"🤠",
    },
    {
        id:3,
        name:"ImotParty",
        kor:"파티",
        emo:"🥳",
    },
    {
        id:4,
        name:"ImotSocool",
        kor:"쏘쿨",
        emo:"😎",
    },
    {
        id:5,
        name:"ImotMenbung",
        kor:"멘붕",
        emo:"😱",
    }
]

export const down_imoticon_path = [
    {
        id:6,
        name:"ImotStumped",
        kor:"난감",
        emo:"😅",
    },
    {
        id:7,
        name:"ImotBigsmile",
        kor:"깔깔",
        emo:"🤣",
    },
    {
        id:8,
        name:"ImotSad",
        kor:"훌쩍",
        emo:"🥲",
    },
    {
        id:9,
        name:"ImotKiss",
        kor:"쪼옥~",
        emo:"😘",
    },
    {
        id:10,
        name:"ImotKidding",
        kor:"매롱",
        emo:"🤪",
    }
]

export const emoji_list = [
    {
        id:1,
        name:"ImotLove",
        kor:"사랑해",
        emo:"😍",

    },
    {
        id:2,
        name:"ImotNice",
        kor:"멋져",
        emo:"🤠",
    },
    {
        id:3,
        name:"ImotParty",
        kor:"파티",
        emo:"🥳",
    },
    {
        id:4,
        name:"ImotSocool",
        kor:"쏘쿨",
        emo:"😎",
    },
    {
        id:5,
        name:"ImotMenbung",
        kor:"멘붕",
        emo:"😱",
    },
    {
        id:6,
        name:"ImotStumped",
        kor:"난감",
        emo:"😅",
    },
    {
        id:7,
        name:"ImotBigsmile",
        kor:"깔깔",
        emo:"🤣",
    },
    {
        id:8,
        name:"ImotSad",
        kor:"훌쩍",
        emo:"🥲",
    },
    {
        id:9,
        name:"ImotKiss",
        kor:"쪼옥~",
        emo:"😘",
    },
    {
        id:10,
        name:"ImotKidding",
        kor:"매롱",
        emo:"🤪",
    }
]